language: python
sudo: false

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py27-django18

    - python: "2.7"
      env: TOX_ENV=py27-django111

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
